# src/main/resources/application.yaml

spring:
  profiles:
    active: dev  # dev será o perfil padrão ao subir a app

  app:
    kafka:
      enabled: true  # <--- IMPORTANTE!

  # Configuração comum a todos os perfis (se quiser)
  jpa:
    properties:
      hibernate.show_sql: false # mostra log SQL no console
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none  # sobrescrito nos perfis dev/test

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: arte-galeria-group
      auto-offset-reset: earliest
